### ISSUE TITLE
Pipeline linked input and output options do not update label

### ISSUE THREAD

**Issue by targos** [neptunejs/larissa-ui#9]
To reproduce:

- Insert a pipeline
- Add an identity node to it
- Change the title of the node to "TEST"
- Go back to the root pipeline
- Select the new pipeline
- Go to the PIPELINE options
- Click on the "Select" menu for linked inputs

The list should show "TEST - value" but has "identity - value" instead

**Comment by targos** [comment]
The problem is that the input candidates are computed when the pipeline changes, not when the corresponding node changes.

**Comment by stropitek** [comment]
```js
    getInputCandidates() {
        const inputs = [];
        for (let node of this._nodes.values()) {
            for (let input of node.inputs.values()) {
                inputs.push({
                    node: node.id,
                    input: input.name
                });
            }
        }
        return inputs;
    }
```
